version: '3.8'

services:
  # Redis Queue Consumer - processes face swap tasks from Upstash Redis
  redis-queue-consumer:
    build: .
    env_file:
      - .env.production
    volumes:
      - ./downloads:/app/downloads
      - ./output:/app/output
    restart: unless-stopped
    # Uses default CMD from Dockerfile: redis_queue_consumer.py

volumes:
  # Volume for temporary downloads (cleaned up automatically)
  downloads:
  # Volume for output files (can be persisted or cleaned up as needed)
  output:
