version: '3.8'

services:
  # Redis Queue Consumer - processes face swap tasks from Upstash Redis
  redis-queue-consumer:
    build: .
    env_file:
      - .env.production
    volumes:
      - ./downloads:/app/downloads
      - ./output:/app/output
    environment:
      # Upstash Redis configuration (required)
      - UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL}
      - UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN}
      
      # Cloudflare R2 configuration (required)
      - R2_ENDPOINT=${R2_ENDPOINT}
      - R2_ACCESS_KEY=${R2_ACCESS_KEY}
      - R2_SECRET_KEY=${R2_SECRET_KEY}
      - R2_BUCKET=${R2_BUCKET}
      - R2_PUBLIC_URL=${R2_PUBLIC_URL}
      
      # API configuration for status updates
      - API_BASE_URL=${API_BASE_URL:-https://aifacesswap.com}
      - WORKER_API_KEY=${WORKER_API_KEY}
      
      # Processing configuration
      - DOWNLOAD_DIR=/app/downloads
      - OUTPUT_DIR=/app/output
      - POLL_INTERVAL=${POLL_INTERVAL:-1.0}
      - BLOCKING_TIMEOUT=${BLOCKING_TIMEOUT:-30.0}
    restart: unless-stopped
    # Uses default CMD from Dockerfile: redis_queue_consumer.py

volumes:
  # Volume for temporary downloads (cleaned up automatically)
  downloads:
  # Volume for output files (can be persisted or cleaned up as needed)
  output:
